"""empty message

Revision ID: 610dd19cc323
Revises: 235ecac7d93a
Create Date: 2018-06-07 14:36:42.968251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '610dd19cc323'
down_revision = '235ecac7d93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showname', sa.String(length=50), nullable=True),
    sa.Column('shownameen', sa.String(length=50), nullable=True),
    sa.Column('director', sa.String(length=20), nullable=True),
    sa.Column('leadingRole', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('screeningmodel', sa.String(length=20), nullable=True),
    sa.Column('openday', sa.DateTime(), nullable=True),
    sa.Column('backgroundpicture', sa.String(length=200), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cinemas')
    op.drop_table('movies')
    op.add_column('t_user', sa.Column('photo1', sa.String(length=200), nullable=True))
    op.add_column('t_user', sa.Column('photo2', sa.String(length=200), nullable=True))
    op.drop_column('t_user', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_url', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('t_user', 'photo2')
    op.drop_column('t_user', 'photo1')
    op.create_table('movies',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('showname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('shownameen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('director', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('leadingRole', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('screeningmodel', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('openday', mysql.DATETIME(), nullable=True),
    sa.Column('backgroundpicture', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('flag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cinemas',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('hallnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('servicecharge', mysql.FLOAT(), nullable=True),
    sa.Column('astrict', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('flag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_movies')
    op.drop_table('t_cinemas')
    # ### end Alembic commands ###
